version: "3.3"

services:
  gplace-redis:
    container_name: gplace-redis
    image: redis:7.2.1-alpine
    restart: always
    ports:
      - ${REDIS_PORT-6479}:6379
    volumes:
      - ./redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD-password}
  gplace-db:
    container_name: gplace-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-password}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT-5476}:5432
  gplace-app:
    container_name: gplace-app
    build:
      context: .
      dockerfile: ./docker/dev/app.dockerfile
    restart: always
    depends_on:
      - gplace-db
    ports:
      - ${STUDIO_PORT-5556}:5555
      - ${DEV_PORT-5176}:5173
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD-password}@gplace-db:5432/postgres
      - APP_ORIGIN=${APP_ORIGIN-http://localhost:5176}
      - PUBLIC_CURRENT_BOARD=${PUBLIC_CURRENT_BOARD?Board Param is required, set to empty string if none yet.}
      - PROD=${PROD-false}
      - REDIS_URL=redis://default:${REDIS_PASSWORD-password}@gplace-redis:6379/0
