name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_PORT: ${{vars.APP_PORT}}
      APP_ORIGIN: ${{vars.APP_ORIGIN}}
      PUBLIC_CURRENT_BOARD: ${{vars.PUBLIC_CURRENT_BOARD}}
      PROD: ${{vars.PROD}}
      REDIS_URL: ${{secrets.REDIS_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx zenstack generate && npx prisma generate
      - run: npm run build --if-present